version: "2.1"
services:
  # https://hub.docker.com/r/itsthenetwork/nfs-server-alpine
  nfs:
    image: itsthenetwork/nfs-server-alpine:12
    container_name: nfs
    restart: unless-stopped
    privileged: true
    environment:
      - SHARED_DIRECTORY=/data
    volumes:
      - ./nfs-server-data:/data
    expose:
      - 2049

  client:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: client
